package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * AreaPrice generated by hbm2java
 */
public class AreaPrice  implements java.io.Serializable {


     private Integer idareaPrice;
     private int zipCodeIdzipCode;
     private double areaPriceAmount;

    public AreaPrice() {
    }

    public AreaPrice(int zipCodeIdzipCode, double areaPriceAmount) {
       this.zipCodeIdzipCode = zipCodeIdzipCode;
       this.areaPriceAmount = areaPriceAmount;
    }
   
    public Integer getIdareaPrice() {
        return this.idareaPrice;
    }
    
    public void setIdareaPrice(Integer idareaPrice) {
        this.idareaPrice = idareaPrice;
    }
    public int getZipCodeIdzipCode() {
        return this.zipCodeIdzipCode;
    }
    
    public void setZipCodeIdzipCode(int zipCodeIdzipCode) {
        this.zipCodeIdzipCode = zipCodeIdzipCode;
    }
    public double getAreaPriceAmount() {
        return this.areaPriceAmount;
    }
    
    public void setAreaPriceAmount(double areaPriceAmount) {
        this.areaPriceAmount = areaPriceAmount;
    }




}


