package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private int idCart;
     private UserLogin userLogin;

    public Cart() {
    }

    public Cart(int idCart, UserLogin userLogin) {
       this.idCart = idCart;
       this.userLogin = userLogin;
    }
   
    public int getIdCart() {
        return this.idCart;
    }
    
    public void setIdCart(int idCart) {
        this.idCart = idCart;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }




}


