package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * CartItemStatus generated by hbm2java
 */
public class CartItemStatus  implements java.io.Serializable {


     private Integer idcartItemStatus;
     private String cartItemName;

    public CartItemStatus() {
    }

    public CartItemStatus(String cartItemName) {
       this.cartItemName = cartItemName;
    }
   
    public Integer getIdcartItemStatus() {
        return this.idcartItemStatus;
    }
    
    public void setIdcartItemStatus(Integer idcartItemStatus) {
        this.idcartItemStatus = idcartItemStatus;
    }
    public String getCartItemName() {
        return this.cartItemName;
    }
    
    public void setCartItemName(String cartItemName) {
        this.cartItemName = cartItemName;
    }




}


