package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CartItem generated by hbm2java
 */
public class CartItem  implements java.io.Serializable {


     private Integer idorder;
     private UserLogin userLogin;
     private PrinterStatus printerStatus;
     private PrinterHasProduct printerHasProduct;
     private Date cartItemDate;
     private int frameTypeIdFrameType;
     private int cartIdCart;
     private int cartItemStatusIdcartItemStatus;

    public CartItem() {
    }

    public CartItem(UserLogin userLogin, PrinterStatus printerStatus, PrinterHasProduct printerHasProduct, Date cartItemDate, int frameTypeIdFrameType, int cartIdCart, int cartItemStatusIdcartItemStatus) {
       this.userLogin = userLogin;
       this.printerStatus = printerStatus;
       this.printerHasProduct = printerHasProduct;
       this.cartItemDate = cartItemDate;
       this.frameTypeIdFrameType = frameTypeIdFrameType;
       this.cartIdCart = cartIdCart;
       this.cartItemStatusIdcartItemStatus = cartItemStatusIdcartItemStatus;
    }
   
    public Integer getIdorder() {
        return this.idorder;
    }
    
    public void setIdorder(Integer idorder) {
        this.idorder = idorder;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public PrinterStatus getPrinterStatus() {
        return this.printerStatus;
    }
    
    public void setPrinterStatus(PrinterStatus printerStatus) {
        this.printerStatus = printerStatus;
    }
    public PrinterHasProduct getPrinterHasProduct() {
        return this.printerHasProduct;
    }
    
    public void setPrinterHasProduct(PrinterHasProduct printerHasProduct) {
        this.printerHasProduct = printerHasProduct;
    }
    public Date getCartItemDate() {
        return this.cartItemDate;
    }
    
    public void setCartItemDate(Date cartItemDate) {
        this.cartItemDate = cartItemDate;
    }
    public int getFrameTypeIdFrameType() {
        return this.frameTypeIdFrameType;
    }
    
    public void setFrameTypeIdFrameType(int frameTypeIdFrameType) {
        this.frameTypeIdFrameType = frameTypeIdFrameType;
    }
    public int getCartIdCart() {
        return this.cartIdCart;
    }
    
    public void setCartIdCart(int cartIdCart) {
        this.cartIdCart = cartIdCart;
    }
    public int getCartItemStatusIdcartItemStatus() {
        return this.cartItemStatusIdcartItemStatus;
    }
    
    public void setCartItemStatusIdcartItemStatus(int cartItemStatusIdcartItemStatus) {
        this.cartItemStatusIdcartItemStatus = cartItemStatusIdcartItemStatus;
    }




}


