package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cateogry generated by hbm2java
 */
public class Cateogry  implements java.io.Serializable {


     private int idcateogry;
     private String categoryName;
     private Set<Product> products = new HashSet<Product>(0);

    public Cateogry() {
    }

	
    public Cateogry(int idcateogry) {
        this.idcateogry = idcateogry;
    }
    public Cateogry(int idcateogry, String categoryName, Set<Product> products) {
       this.idcateogry = idcateogry;
       this.categoryName = categoryName;
       this.products = products;
    }
   
    public int getIdcateogry() {
        return this.idcateogry;
    }
    
    public void setIdcateogry(int idcateogry) {
        this.idcateogry = idcateogry;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


