package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * ComplaintSubject generated by hbm2java
 */
public class ComplaintSubject  implements java.io.Serializable {


     private int idcomplaintSubject;
     private UserLogin userLogin;
     private String complaintSubjectName;

    public ComplaintSubject() {
    }

	
    public ComplaintSubject(int idcomplaintSubject, UserLogin userLogin) {
        this.idcomplaintSubject = idcomplaintSubject;
        this.userLogin = userLogin;
    }
    public ComplaintSubject(int idcomplaintSubject, UserLogin userLogin, String complaintSubjectName) {
       this.idcomplaintSubject = idcomplaintSubject;
       this.userLogin = userLogin;
       this.complaintSubjectName = complaintSubjectName;
    }
   
    public int getIdcomplaintSubject() {
        return this.idcomplaintSubject;
    }
    
    public void setIdcomplaintSubject(int idcomplaintSubject) {
        this.idcomplaintSubject = idcomplaintSubject;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public String getComplaintSubjectName() {
        return this.complaintSubjectName;
    }
    
    public void setComplaintSubjectName(String complaintSubjectName) {
        this.complaintSubjectName = complaintSubjectName;
    }




}


