package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private int iddelivery;
     private UserLogin userLogin;
     private String deliveryFullName;
     private String deliveryAddNo;
     private String deliveryAddSt1;
     private String deliveryAddSt2;
     private String deliveryAddCity;
     private int zipCodeIdzipCode;
     private String deliveryTp1;
     private String deliveryTp2;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Delivery() {
    }

	
    public Delivery(int iddelivery, UserLogin userLogin, int zipCodeIdzipCode) {
        this.iddelivery = iddelivery;
        this.userLogin = userLogin;
        this.zipCodeIdzipCode = zipCodeIdzipCode;
    }
    public Delivery(int iddelivery, UserLogin userLogin, String deliveryFullName, String deliveryAddNo, String deliveryAddSt1, String deliveryAddSt2, String deliveryAddCity, int zipCodeIdzipCode, String deliveryTp1, String deliveryTp2, Set<Transaction> transactions) {
       this.iddelivery = iddelivery;
       this.userLogin = userLogin;
       this.deliveryFullName = deliveryFullName;
       this.deliveryAddNo = deliveryAddNo;
       this.deliveryAddSt1 = deliveryAddSt1;
       this.deliveryAddSt2 = deliveryAddSt2;
       this.deliveryAddCity = deliveryAddCity;
       this.zipCodeIdzipCode = zipCodeIdzipCode;
       this.deliveryTp1 = deliveryTp1;
       this.deliveryTp2 = deliveryTp2;
       this.transactions = transactions;
    }
   
    public int getIddelivery() {
        return this.iddelivery;
    }
    
    public void setIddelivery(int iddelivery) {
        this.iddelivery = iddelivery;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public String getDeliveryFullName() {
        return this.deliveryFullName;
    }
    
    public void setDeliveryFullName(String deliveryFullName) {
        this.deliveryFullName = deliveryFullName;
    }
    public String getDeliveryAddNo() {
        return this.deliveryAddNo;
    }
    
    public void setDeliveryAddNo(String deliveryAddNo) {
        this.deliveryAddNo = deliveryAddNo;
    }
    public String getDeliveryAddSt1() {
        return this.deliveryAddSt1;
    }
    
    public void setDeliveryAddSt1(String deliveryAddSt1) {
        this.deliveryAddSt1 = deliveryAddSt1;
    }
    public String getDeliveryAddSt2() {
        return this.deliveryAddSt2;
    }
    
    public void setDeliveryAddSt2(String deliveryAddSt2) {
        this.deliveryAddSt2 = deliveryAddSt2;
    }
    public String getDeliveryAddCity() {
        return this.deliveryAddCity;
    }
    
    public void setDeliveryAddCity(String deliveryAddCity) {
        this.deliveryAddCity = deliveryAddCity;
    }
    public int getZipCodeIdzipCode() {
        return this.zipCodeIdzipCode;
    }
    
    public void setZipCodeIdzipCode(int zipCodeIdzipCode) {
        this.zipCodeIdzipCode = zipCodeIdzipCode;
    }
    public String getDeliveryTp1() {
        return this.deliveryTp1;
    }
    
    public void setDeliveryTp1(String deliveryTp1) {
        this.deliveryTp1 = deliveryTp1;
    }
    public String getDeliveryTp2() {
        return this.deliveryTp2;
    }
    
    public void setDeliveryTp2(String deliveryTp2) {
        this.deliveryTp2 = deliveryTp2;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


