package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * FrameStatus generated by hbm2java
 */
public class FrameStatus  implements java.io.Serializable {


     private int idFrameStatus;
     private String frameStatusName;

    public FrameStatus() {
    }

	
    public FrameStatus(int idFrameStatus) {
        this.idFrameStatus = idFrameStatus;
    }
    public FrameStatus(int idFrameStatus, String frameStatusName) {
       this.idFrameStatus = idFrameStatus;
       this.frameStatusName = frameStatusName;
    }
   
    public int getIdFrameStatus() {
        return this.idFrameStatus;
    }
    
    public void setIdFrameStatus(int idFrameStatus) {
        this.idFrameStatus = idFrameStatus;
    }
    public String getFrameStatusName() {
        return this.frameStatusName;
    }
    
    public void setFrameStatusName(String frameStatusName) {
        this.frameStatusName = frameStatusName;
    }




}


