package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * FrameType generated by hbm2java
 */
public class FrameType  implements java.io.Serializable {


     private int idFrameType;
     private UserLogin userLogin;
     private String frameTypeName;

    public FrameType() {
    }

	
    public FrameType(int idFrameType, UserLogin userLogin) {
        this.idFrameType = idFrameType;
        this.userLogin = userLogin;
    }
    public FrameType(int idFrameType, UserLogin userLogin, String frameTypeName) {
       this.idFrameType = idFrameType;
       this.userLogin = userLogin;
       this.frameTypeName = frameTypeName;
    }
   
    public int getIdFrameType() {
        return this.idFrameType;
    }
    
    public void setIdFrameType(int idFrameType) {
        this.idFrameType = idFrameType;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public String getFrameTypeName() {
        return this.frameTypeName;
    }
    
    public void setFrameTypeName(String frameTypeName) {
        this.frameTypeName = frameTypeName;
    }




}


