package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * InterfacesStatus generated by hbm2java
 */
public class InterfacesStatus  implements java.io.Serializable {


     private int idinterfacesStatus;
     private String interfacesStatusName;
     private Set<Interfaces> interfaceses = new HashSet<Interfaces>(0);

    public InterfacesStatus() {
    }

	
    public InterfacesStatus(int idinterfacesStatus) {
        this.idinterfacesStatus = idinterfacesStatus;
    }
    public InterfacesStatus(int idinterfacesStatus, String interfacesStatusName, Set<Interfaces> interfaceses) {
       this.idinterfacesStatus = idinterfacesStatus;
       this.interfacesStatusName = interfacesStatusName;
       this.interfaceses = interfaceses;
    }
   
    public int getIdinterfacesStatus() {
        return this.idinterfacesStatus;
    }
    
    public void setIdinterfacesStatus(int idinterfacesStatus) {
        this.idinterfacesStatus = idinterfacesStatus;
    }
    public String getInterfacesStatusName() {
        return this.interfacesStatusName;
    }
    
    public void setInterfacesStatusName(String interfacesStatusName) {
        this.interfacesStatusName = interfacesStatusName;
    }
    public Set<Interfaces> getInterfaceses() {
        return this.interfaceses;
    }
    
    public void setInterfaceses(Set<Interfaces> interfaceses) {
        this.interfaceses = interfaceses;
    }




}


