package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * LoginSessions generated by hbm2java
 */
public class LoginSessions  implements java.io.Serializable {


     private Integer idloginSessions;
     private UserLogin userLogin;
     private String ipAddress;
     private Date inTime;
     private Date outTime;

    public LoginSessions() {
    }

	
    public LoginSessions(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public LoginSessions(UserLogin userLogin, String ipAddress, Date inTime, Date outTime) {
       this.userLogin = userLogin;
       this.ipAddress = ipAddress;
       this.inTime = inTime;
       this.outTime = outTime;
    }
   
    public Integer getIdloginSessions() {
        return this.idloginSessions;
    }
    
    public void setIdloginSessions(Integer idloginSessions) {
        this.idloginSessions = idloginSessions;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }




}


