package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PrinterHasProduct generated by hbm2java
 */
public class PrinterHasProduct  implements java.io.Serializable {


     private Integer printerHasProductid;
     private ProductStatus productStatus;
     private UserLogin userLogin;
     private Product product;
     private double price;
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);

    public PrinterHasProduct() {
    }

	
    public PrinterHasProduct(ProductStatus productStatus, UserLogin userLogin, Product product, double price) {
        this.productStatus = productStatus;
        this.userLogin = userLogin;
        this.product = product;
        this.price = price;
    }
    public PrinterHasProduct(ProductStatus productStatus, UserLogin userLogin, Product product, double price, Set<CartItem> cartItems) {
       this.productStatus = productStatus;
       this.userLogin = userLogin;
       this.product = product;
       this.price = price;
       this.cartItems = cartItems;
    }
   
    public Integer getPrinterHasProductid() {
        return this.printerHasProductid;
    }
    
    public void setPrinterHasProductid(Integer printerHasProductid) {
        this.printerHasProductid = printerHasProductid;
    }
    public ProductStatus getProductStatus() {
        return this.productStatus;
    }
    
    public void setProductStatus(ProductStatus productStatus) {
        this.productStatus = productStatus;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }




}


