package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PrinterStatus generated by hbm2java
 */
public class PrinterStatus  implements java.io.Serializable {


     private Integer idprinterStatus;
     private String printerStatusName;
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);

    public PrinterStatus() {
    }

    public PrinterStatus(String printerStatusName, Set<CartItem> cartItems) {
       this.printerStatusName = printerStatusName;
       this.cartItems = cartItems;
    }
   
    public Integer getIdprinterStatus() {
        return this.idprinterStatus;
    }
    
    public void setIdprinterStatus(Integer idprinterStatus) {
        this.idprinterStatus = idprinterStatus;
    }
    public String getPrinterStatusName() {
        return this.printerStatusName;
    }
    
    public void setPrinterStatusName(String printerStatusName) {
        this.printerStatusName = printerStatusName;
    }
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }




}


