package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * Privilages generated by hbm2java
 */
public class Privilages  implements java.io.Serializable {


     private Integer idprivilages;
     private UserType userType;
     private Interfaces interfaces;

    public Privilages() {
    }

    public Privilages(UserType userType, Interfaces interfaces) {
       this.userType = userType;
       this.interfaces = interfaces;
    }
   
    public Integer getIdprivilages() {
        return this.idprivilages;
    }
    
    public void setIdprivilages(Integer idprivilages) {
        this.idprivilages = idprivilages;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }




}


