package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * ProductDeactivate generated by hbm2java
 */
public class ProductDeactivate  implements java.io.Serializable {


     private Integer idproductDeactivate;
     private Product product;
     private String productDeactivateReason;
     private Date productDeactivateTimeDate;

    public ProductDeactivate() {
    }

    public ProductDeactivate(Product product, String productDeactivateReason, Date productDeactivateTimeDate) {
       this.product = product;
       this.productDeactivateReason = productDeactivateReason;
       this.productDeactivateTimeDate = productDeactivateTimeDate;
    }
   
    public Integer getIdproductDeactivate() {
        return this.idproductDeactivate;
    }
    
    public void setIdproductDeactivate(Integer idproductDeactivate) {
        this.idproductDeactivate = idproductDeactivate;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getProductDeactivateReason() {
        return this.productDeactivateReason;
    }
    
    public void setProductDeactivateReason(String productDeactivateReason) {
        this.productDeactivateReason = productDeactivateReason;
    }
    public Date getProductDeactivateTimeDate() {
        return this.productDeactivateTimeDate;
    }
    
    public void setProductDeactivateTimeDate(Date productDeactivateTimeDate) {
        this.productDeactivateTimeDate = productDeactivateTimeDate;
    }




}


