package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ProductStatus generated by hbm2java
 */
public class ProductStatus  implements java.io.Serializable {


     private int idproductStatus;
     private String productStatusName;
     private Set<PrinterHasProduct> printerHasProducts = new HashSet<PrinterHasProduct>(0);

    public ProductStatus() {
    }

	
    public ProductStatus(int idproductStatus) {
        this.idproductStatus = idproductStatus;
    }
    public ProductStatus(int idproductStatus, String productStatusName, Set<PrinterHasProduct> printerHasProducts) {
       this.idproductStatus = idproductStatus;
       this.productStatusName = productStatusName;
       this.printerHasProducts = printerHasProducts;
    }
   
    public int getIdproductStatus() {
        return this.idproductStatus;
    }
    
    public void setIdproductStatus(int idproductStatus) {
        this.idproductStatus = idproductStatus;
    }
    public String getProductStatusName() {
        return this.productStatusName;
    }
    
    public void setProductStatusName(String productStatusName) {
        this.productStatusName = productStatusName;
    }
    public Set<PrinterHasProduct> getPrinterHasProducts() {
        return this.printerHasProducts;
    }
    
    public void setPrinterHasProducts(Set<PrinterHasProduct> printerHasProducts) {
        this.printerHasProducts = printerHasProducts;
    }




}


