package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * ProductHasAddOn generated by hbm2java
 */
public class ProductHasAddOn  implements java.io.Serializable {


     private Integer idproductHasAddOn;
     private Product product;
     private int addOnIdAddOn;

    public ProductHasAddOn() {
    }

    public ProductHasAddOn(Product product, int addOnIdAddOn) {
       this.product = product;
       this.addOnIdAddOn = addOnIdAddOn;
    }
   
    public Integer getIdproductHasAddOn() {
        return this.idproductHasAddOn;
    }
    
    public void setIdproductHasAddOn(Integer idproductHasAddOn) {
        this.idproductHasAddOn = idproductHasAddOn;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getAddOnIdAddOn() {
        return this.addOnIdAddOn;
    }
    
    public void setAddOnIdAddOn(int addOnIdAddOn) {
        this.addOnIdAddOn = addOnIdAddOn;
    }




}


