package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategory generated by hbm2java
 */
public class Subcategory  implements java.io.Serializable {


     private Integer idsubcategory;
     private String subcategoryName;
     private Set<ProductHasSubcategory> productHasSubcategories = new HashSet<ProductHasSubcategory>(0);

    public Subcategory() {
    }

    public Subcategory(String subcategoryName, Set<ProductHasSubcategory> productHasSubcategories) {
       this.subcategoryName = subcategoryName;
       this.productHasSubcategories = productHasSubcategories;
    }
   
    public Integer getIdsubcategory() {
        return this.idsubcategory;
    }
    
    public void setIdsubcategory(Integer idsubcategory) {
        this.idsubcategory = idsubcategory;
    }
    public String getSubcategoryName() {
        return this.subcategoryName;
    }
    
    public void setSubcategoryName(String subcategoryName) {
        this.subcategoryName = subcategoryName;
    }
    public Set<ProductHasSubcategory> getProductHasSubcategories() {
        return this.productHasSubcategories;
    }
    
    public void setProductHasSubcategories(Set<ProductHasSubcategory> productHasSubcategories) {
        this.productHasSubcategories = productHasSubcategories;
    }




}


