package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private Integer idtransaction;
     private Delivery delivery;
     private TransactionStatus transactionStatus;
     private Date transactionDate;
     private String transactionCardNo;
     private String transactionCvc;
     private String transactionExpireYear;
     private String transactionExpireMonth;
     private Set<TransactionHasCartItem> transactionHasCartItems = new HashSet<TransactionHasCartItem>(0);

    public Transaction() {
    }

	
    public Transaction(Delivery delivery, TransactionStatus transactionStatus) {
        this.delivery = delivery;
        this.transactionStatus = transactionStatus;
    }
    public Transaction(Delivery delivery, TransactionStatus transactionStatus, Date transactionDate, String transactionCardNo, String transactionCvc, String transactionExpireYear, String transactionExpireMonth, Set<TransactionHasCartItem> transactionHasCartItems) {
       this.delivery = delivery;
       this.transactionStatus = transactionStatus;
       this.transactionDate = transactionDate;
       this.transactionCardNo = transactionCardNo;
       this.transactionCvc = transactionCvc;
       this.transactionExpireYear = transactionExpireYear;
       this.transactionExpireMonth = transactionExpireMonth;
       this.transactionHasCartItems = transactionHasCartItems;
    }
   
    public Integer getIdtransaction() {
        return this.idtransaction;
    }
    
    public void setIdtransaction(Integer idtransaction) {
        this.idtransaction = idtransaction;
    }
    public Delivery getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Delivery delivery) {
        this.delivery = delivery;
    }
    public TransactionStatus getTransactionStatus() {
        return this.transactionStatus;
    }
    
    public void setTransactionStatus(TransactionStatus transactionStatus) {
        this.transactionStatus = transactionStatus;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getTransactionCardNo() {
        return this.transactionCardNo;
    }
    
    public void setTransactionCardNo(String transactionCardNo) {
        this.transactionCardNo = transactionCardNo;
    }
    public String getTransactionCvc() {
        return this.transactionCvc;
    }
    
    public void setTransactionCvc(String transactionCvc) {
        this.transactionCvc = transactionCvc;
    }
    public String getTransactionExpireYear() {
        return this.transactionExpireYear;
    }
    
    public void setTransactionExpireYear(String transactionExpireYear) {
        this.transactionExpireYear = transactionExpireYear;
    }
    public String getTransactionExpireMonth() {
        return this.transactionExpireMonth;
    }
    
    public void setTransactionExpireMonth(String transactionExpireMonth) {
        this.transactionExpireMonth = transactionExpireMonth;
    }
    public Set<TransactionHasCartItem> getTransactionHasCartItems() {
        return this.transactionHasCartItems;
    }
    
    public void setTransactionHasCartItems(Set<TransactionHasCartItem> transactionHasCartItems) {
        this.transactionHasCartItems = transactionHasCartItems;
    }




}


