package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * UserTypeHasUserSpecification generated by hbm2java
 */
public class UserTypeHasUserSpecification  implements java.io.Serializable {


     private Integer iduserTypeHasUserSpecification;
     private UserType userType;
     private UserLogin userLogin;
     private int userSpecificationIduserSpecification;
     private String value;

    public UserTypeHasUserSpecification() {
    }

    public UserTypeHasUserSpecification(UserType userType, UserLogin userLogin, int userSpecificationIduserSpecification, String value) {
       this.userType = userType;
       this.userLogin = userLogin;
       this.userSpecificationIduserSpecification = userSpecificationIduserSpecification;
       this.value = value;
    }
   
    public Integer getIduserTypeHasUserSpecification() {
        return this.iduserTypeHasUserSpecification;
    }
    
    public void setIduserTypeHasUserSpecification(Integer iduserTypeHasUserSpecification) {
        this.iduserTypeHasUserSpecification = iduserTypeHasUserSpecification;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public int getUserSpecificationIduserSpecification() {
        return this.userSpecificationIduserSpecification;
    }
    
    public void setUserSpecificationIduserSpecification(int userSpecificationIduserSpecification) {
        this.userSpecificationIduserSpecification = userSpecificationIduserSpecification;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


