package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * UserBackup generated by hbm2java
 */
public class UserBackup  implements java.io.Serializable {


     private int iduserBackup;
     private UserLogin userLogin;
     private String userRegistrationkey;
     private String userForgetpasswordkey;

    public UserBackup() {
    }

	
    public UserBackup(int iduserBackup, UserLogin userLogin) {
        this.iduserBackup = iduserBackup;
        this.userLogin = userLogin;
    }
    public UserBackup(int iduserBackup, UserLogin userLogin, String userRegistrationkey, String userForgetpasswordkey) {
       this.iduserBackup = iduserBackup;
       this.userLogin = userLogin;
       this.userRegistrationkey = userRegistrationkey;
       this.userForgetpasswordkey = userForgetpasswordkey;
    }
   
    public int getIduserBackup() {
        return this.iduserBackup;
    }
    
    public void setIduserBackup(int iduserBackup) {
        this.iduserBackup = iduserBackup;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public String getUserRegistrationkey() {
        return this.userRegistrationkey;
    }
    
    public void setUserRegistrationkey(String userRegistrationkey) {
        this.userRegistrationkey = userRegistrationkey;
    }
    public String getUserForgetpasswordkey() {
        return this.userForgetpasswordkey;
    }
    
    public void setUserForgetpasswordkey(String userForgetpasswordkey) {
        this.userForgetpasswordkey = userForgetpasswordkey;
    }




}


