package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserStatus generated by hbm2java
 */
public class UserStatus  implements java.io.Serializable {


     private Integer iduserStatus;
     private String userStatusName;
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);

    public UserStatus() {
    }

    public UserStatus(String userStatusName, Set<UserLogin> userLogins) {
       this.userStatusName = userStatusName;
       this.userLogins = userLogins;
    }
   
    public Integer getIduserStatus() {
        return this.iduserStatus;
    }
    
    public void setIduserStatus(Integer iduserStatus) {
        this.iduserStatus = iduserStatus;
    }
    public String getUserStatusName() {
        return this.userStatusName;
    }
    
    public void setUserStatusName(String userStatusName) {
        this.userStatusName = userStatusName;
    }
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }




}


