package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer iduserType;
     private String typeName;
     private Set<UserLogin> userLogins = new HashSet<UserLogin>(0);
     private Set<UserTypeHasUserSpecification> userTypeHasUserSpecifications = new HashSet<UserTypeHasUserSpecification>(0);
     private Set<Privilages> privilageses = new HashSet<Privilages>(0);

    public UserType() {
    }

    public UserType(String typeName, Set<UserLogin> userLogins, Set<UserTypeHasUserSpecification> userTypeHasUserSpecifications, Set<Privilages> privilageses) {
       this.typeName = typeName;
       this.userLogins = userLogins;
       this.userTypeHasUserSpecifications = userTypeHasUserSpecifications;
       this.privilageses = privilageses;
    }
   
    public Integer getIduserType() {
        return this.iduserType;
    }
    
    public void setIduserType(Integer iduserType) {
        this.iduserType = iduserType;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set<UserLogin> getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set<UserLogin> userLogins) {
        this.userLogins = userLogins;
    }
    public Set<UserTypeHasUserSpecification> getUserTypeHasUserSpecifications() {
        return this.userTypeHasUserSpecifications;
    }
    
    public void setUserTypeHasUserSpecifications(Set<UserTypeHasUserSpecification> userTypeHasUserSpecifications) {
        this.userTypeHasUserSpecifications = userTypeHasUserSpecifications;
    }
    public Set<Privilages> getPrivilageses() {
        return this.privilageses;
    }
    
    public void setPrivilageses(Set<Privilages> privilageses) {
        this.privilageses = privilageses;
    }




}


