package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * UserSpecification generated by hbm2java
 */
public class UserSpecification  implements java.io.Serializable {


     private int iduserSpecification;
     private String userSpecificationName;
     private String userSpecificationcol;

    public UserSpecification() {
    }

	
    public UserSpecification(int iduserSpecification) {
        this.iduserSpecification = iduserSpecification;
    }
    public UserSpecification(int iduserSpecification, String userSpecificationName, String userSpecificationcol) {
       this.iduserSpecification = iduserSpecification;
       this.userSpecificationName = userSpecificationName;
       this.userSpecificationcol = userSpecificationcol;
    }
   
    public int getIduserSpecification() {
        return this.iduserSpecification;
    }
    
    public void setIduserSpecification(int iduserSpecification) {
        this.iduserSpecification = iduserSpecification;
    }
    public String getUserSpecificationName() {
        return this.userSpecificationName;
    }
    
    public void setUserSpecificationName(String userSpecificationName) {
        this.userSpecificationName = userSpecificationName;
    }
    public String getUserSpecificationcol() {
        return this.userSpecificationcol;
    }
    
    public void setUserSpecificationcol(String userSpecificationcol) {
        this.userSpecificationcol = userSpecificationcol;
    }




}


