package POJOS;
// Generated Jan 5, 2018 12:55:52 PM by Hibernate Tools 3.6.0



/**
 * ZipCode generated by hbm2java
 */
public class ZipCode  implements java.io.Serializable {


     private Integer idzipCode;
     private String zipCode;

    public ZipCode() {
    }

    public ZipCode(String zipCode) {
       this.zipCode = zipCode;
    }
   
    public Integer getIdzipCode() {
        return this.idzipCode;
    }
    
    public void setIdzipCode(Integer idzipCode) {
        this.idzipCode = idzipCode;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }




}


